import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav/NavBar";
import DataContext from "./Context/DataContext";
import { ToastContainer } from "react-toastify";
import Footer from "./components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit-Log-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <DataContext >
          <div className="navigationBar">
            <NavBar />
          </div>
          {children}
        </DataContext>
        <div className="footer bg-gray-900">
          <Footer />
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
